extern char* resources;

#define NAR_MODEL_VERT (resources + 4)
#define NAR_MODEL_FRAG (resources + 421)
#define NAR_UI_VERT (resources + 512)
#define NAR_UI_FRAG (resources + 893)
#define NAR_PCCUBE_VERT (resources + 1097)
#define NAR_PCCUBE_FRAG (resources + 1588)
#define NAR_CROSSHAIR_VERT (resources + 1770)
#define NAR_CROSSHAIR_FRAG (resources + 1862)
#define NAR_TMAP_TEX_VERT (resources + 1953)
#define NAR_TMAP_TEX_FRAG (resources + 2045)
#define NAR_VOXEL_ATLAS (resources + 2136)
#define NAR_VOXEL_ATLAS_UVS (resources + 19708)
#define NAR_VPASS_VERT (resources + 20032)
#define NAR_VPASS_FRAG (resources + 20332)
#define NAR_VOXEL_VERT (resources + 20496)
#define NAR_VOXEL_FRAG (resources + 21226)
#define NAR_VOXEL_ARR (resources + 21468)
