extern char* resources;

#define NAR_MODEL_VERT (resources + 4)
#define NAR_MODEL_FRAG (resources + 421)
#define NAR_UI_VERT (resources + 512)
#define NAR_UI_FRAG (resources + 893)
#define NAR_PCCUBE_VERT (resources + 1097)
#define NAR_PCCUBE_FRAG (resources + 1588)
#define NAR_CROSSHAIR_VERT (resources + 1770)
#define NAR_CROSSHAIR_FRAG (resources + 1862)
#define NAR_VOXEL_ATLAS (resources + 1953)
#define NAR_VOXEL_ATLAS_UVS (resources + 19525)
#define NAR_VPASS_VERT (resources + 19849)
#define NAR_VPASS_FRAG (resources + 20149)
#define NAR_VOXEL_VERT (resources + 20313)
#define NAR_VOXEL_FRAG (resources + 21043)
#define NAR_VOXEL_ARR (resources + 21285)
